export const SA_FISH_SPECIES = [
  'Cob (Kob)',
  'Steenbras',
  'Rockcod',
  'Shad (Elf)',
  'Sharks',
  'Blacktail (Dassie)',
  'Yellowtail',
  'White Steenbras',
  'Red Steenbras',
  'Galjoen',
  'Snoek',
  'Cape Salmon (Geelbek)',
  'Bronze Bream',
  'Spotted Grunter',
  'Springer (Garfish)',
  'Catfish',
  'Stumpnose',
  'Musselcracker',
  'Poenskop',
  'Kingfish (Leervis)',
  'Garrick',
  'Dorado (Mahi-Mahi)',
  'Tuna (Yellowfin)',
  'Tuna (Bluefin)',
  'Other',
]

export const BAIT_OPTIONS = [
  'Sardine (Pilchard)',
  'Chokka (Squid)',
  'Bloodworm',
  'Sandworm (Mudprawn)',
  'White Mussel',
  'Crab',
  'Mackerel',
  'Livebait',
  'Prawn',
  'Shrimp',
  'Lure (Soft)',
  'Lure (Hard)',
  'Spoon',
  'Fly',
  'Other',
]

export const TIDE_TYPES = ['Incoming', 'Outgoing', 'High Slack', 'Low Slack']

export const MOON_PHASES = [
  { name: 'New Moon', emoji: '🌑', min: 0, max: 0.0625 },
  { name: 'Waxing Crescent', emoji: '🌒', min: 0.0625, max: 0.1875 },
  { name: 'First Quarter', emoji: '🌓', min: 0.1875, max: 0.3125 },
  { name: 'Waxing Gibbous', emoji: '🌔', min: 0.3125, max: 0.4375 },
  { name: 'Full Moon', emoji: '🌕', min: 0.4375, max: 0.5625 },
  { name: 'Waning Gibbous', emoji: '🌖', min: 0.5625, max: 0.6875 },
  { name: 'Last Quarter', emoji: '🌗', min: 0.6875, max: 0.8125 },
  { name: 'Waning Crescent', emoji: '🌘', min: 0.8125, max: 1 },
]

export const SA_LOCATIONS = [
  'Cape Town (Boulders)',
  'Cape Town (Hout Bay)',
  'Cape Town (Kalk Bay)',
  'Cape Town (Sea Point)',
  'Cape Town (Milnerton)',
  'Cape Town (Strand)',
  'Cape Town (Gordons Bay)',
  'Cape Town (Hermanus)',
  'Gansbaai',
  'Struisbaai',
  "L'Agulhas",
  'Arniston',
  'Mossel Bay',
  'Knysna',
  'Plettenberg Bay',
  'Port Elizabeth (Gqeberha)',
  'East London',
  'Coffee Bay',
  'Port St Johns',
  'Durban (Bluff)',
  'Durban (Addington)',
  'Ballito',
  'Salt Rock',
  'Scottsburgh',
  'Margate',
  'Sodwana Bay',
  'Langebaan',
  'Paternoster',
  "Lambert's Bay",
  'Other',
]
